version: '3.7'

services:
  logmanager:
    container_name: "logmgr"
    image: logmgr
    volumes: 
      - /home/joseph/Documents/gmg/logs:/logs
    build:
      context: ./cmd/logmgr/
      dockerfile: Dockerfile
    ports: 
      - "8083"
      - "8084"    
    environment:
      - LogInPorts=:8083 :8084 :8085
    #env_file: .env

  reverseproxy:
    container_name: "rvprox"
    image: rvprox
    build:
      context: ./cmd/rvprox/
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - ProxyInPorts=rvprox:8080
      - ProxyOutPorts=server_1:8081 server_1:8082 server_2:8086 server_2:8087
      - ProxyLogPort=logmanager:8083
    #env_file: .env
    depends_on: 
      - server_1
      - server_2
      - logmanager

  server_1:
    container_name: "srvr_1"
    image: srvr
    volumes: 
      - /home/joseph/Documents/gmg/Server_1:/downloads
    build: 
      context: ./cmd/server/
      dockerfile: Dockerfile
    ports:
      - "8081"
      - "8082"
    environment:
      - ServerInPorts=:8081 :8082
      - ServerLogPort=logmanager:8084
    #env_file: .env
    depends_on: 
      - logmanager

  server_2:
    container_name: "srvr_2"
    image: srvr
    volumes: 
      - /home/joseph/Documents/gmg/Server_2:/downloads
    build: 
      context: ./cmd/server/
      dockerfile: Dockerfile
    ports:
      - "8086"
      - "8087"
    environment:
      - ServerInPorts=:8086 :8087
      - ServerLogPort=logmanager:8085
    #env_file: .env
    depends_on: 
      - logmanager