version: '3.7'

services:
  logmanager:
    image: logmanager
    volumes: 
      - /home/joseph/Documents/gmg/Log_Manager/:/Log_Manager
    build:
      context: ./cmd/logmgr/
      dockerfile: Dockerfile
    ports: 
      - "8083"
      - "8084"    
    environment:
      - fileSave=true
      - LogInPorts=:8083 :8084
    #env_file: .env


  reverseproxy:
    image: reverseproxy
    build:
      context: ./cmd/rvprox/
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      - ProxyInPorts=reverseproxy:8080
      - ProxyOutPorts=server:8081 server:8082
      - ProxyLogPort=logmanager:8083
    #env_file: .env
    depends_on: 
      - server
      - logmanager

  server:
    image: server
    volumes: 
      - /home/joseph/Documents/gmg/Server/:/Server
    build: 
      context: ./cmd/server/
      dockerfile: Dockerfile
    ports:
      - "8081"
      - "8082"
    environment:
      - ServerInPorts=:8081 :8082
      - ServerLogPort=logmanager:8084
    #env_file: .env
    depends_on: 
      - logmanager